import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { QueryProvider } from "@/components/providers/query-provider";
import { Wrapper } from "@/components/wrapper";
import { Navigation } from "@/components/navigation/navigation";

import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";

import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/footer/footer";
import PremiumModal from "@/components/PREMIUM/premium-modal";
import SubscriptionLevelProvider from "@/components/PREMIUM/subscription-level-provider";
import { getUserSubscriptionLevel } from "@/components/PREMIUM/subscriptions";
import { auth } from "@clerk/nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();

  if (!userId) {
    return null;
  }

  const userSubscriptionLevel = await getUserSubscriptionLevel(userId);
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SubscriptionLevelProvider userSubscriptionLevel={userSubscriptionLevel}>
                <Wrapper>
                  <Navigation />
                  <main>{children}</main>
                  <PremiumModal />
                  <Toaster />
                </Wrapper>
              </SubscriptionLevelProvider>
              <Footer />
            </ThemeProvider>
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
